server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: path_route
            uri: lb://authentication-service
            predicates:
              - Path=/authenticationService/**
        - id: path_route
            uri: lb://matchmaking-service
            predicates:
              - Path=/matchmakingService/**
        - id: path_route
            uri: lb://scoreboard-service
            predicates:
              - Path=/scoreboardService/**
        - id: path_route
            uri: lb://gameinstance-service
            predicates:
              - Path=/gameinstanceService/**
